name: Publish Docs
on:
  push:
    branches: 
      - preprod
    paths:
      - website/**
jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install mkdocs-material
    - run: rm -rf ./dist
    - run: mkdocs build --no-directory-urls -d dist

  deploy-preprod:
    name: Deploy Preprod
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/preprod'
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'dist'
        DEST_DIR: 'preprod'

  deploy-cloudfront:
    name: Invalidate CloudFront
    needs: [build, deploy-preprod]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/preprod'
    steps:
    - uses: chetan/invalidate-cloudfront-action@v2
      env:
        PATHS: '/preprod/*'
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
